### PR TITLE
[AIA-260] Add liveness agent data

### PR DESCRIPTION
**Pull request by afiune**
tenor-222164271

Signed-off-by: Salim Afiune <afiune@chef.io>

### CODE REVIEW

**Review by lancewf — APPROVED** [review]
tenor 6

**Review by jeremiahsnapp — CHANGES_REQUESTED** [review]
Can you add the new config to the habitat plan?

**Comment by afiune** [comment]
@jeremiahsnapp done! 🎉

**Review by jeremiahsnapp — APPROVED** [review]

**Comment by afiune** [comment]
Habitat package built and uploaded to the depot!
```
✓ Uploaded chef/chef-load/4.0.0/20180510205947
```

tenor-125715072

**Pull request merged**
